id: P009483
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14603
  title: ཁྱིམ་གཞིས།
  author: ''
  volumes:
    ca16e50b65f9407ab3e66614a3457d34:
      image_group_id: I1KG21209
      title: ''
      volume_number: 1
      total_pages: 660
      base_file: v001.txt
